# Site settings
title: human crafted
email: your-email@example.com
description: >-
  A product design studio specializing in the rapid realization of ideas.
baseurl: "/Human-Crafted-Home" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - .obsidian/
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md

# Collections for organized content
collections:
  docs:
    output: true
    permalink: /:slug/
  posts:
    output: true
  projects:
    output: true
    permalink: /:slug/

# Obsidian-friendly settings
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false

# GitHub Pages compatible plugins only