# Site settings
title: Human Crafted Home
email: your-email@example.com
description: >-
  A website built with Jekyll, managed with Obsidian, and deployed via GitHub Pages.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - .obsidian/
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md

# Collections for organized content
collections:
  posts:
    output: true
    permalink: /:categories/:year/:month/:day/:title/

# Obsidian-friendly settings
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false

# Enable wikilinks (Obsidian-style [[links]])
plugins:
  - jekyll-wikilinks